-- Patch for already-seeded environments only.
--
-- Syncs the Health Event Details section's section_ui_schema to the canonical
-- definition in g2p_register_sections.sql (line
-- 'livestock_health_event_details_section_01'). The seed only INSERTs and never
-- touches an existing row, so environments seeded before that line changed
-- keep the old dialog forever; this re-applies the whole schema by section_id.
--
-- Why: the official staff-ui cannot fill a dialog column from another
-- section's rows ("sibling-table" source) nor cascade one dialog column from
-- another, so the Ear Tag picker rendered EMPTY (and, on Vaccination, the
-- Vaccine list too). Ear Tag is now a text input (server-checked against this
-- submission's animals), Vaccine the plain VACCINE_TYPE list (server-checked
-- against the animal's species), Species is filled by the server from the
-- animal, and dialog conditions use operators the official UI supports.
-- Also: Notifiable Disease / Pregnancy Confirmed are required only while
-- their show-condition holds (conditional "require" action, like
-- disease_type) — a hidden-but-required radio blocked every non-DISEASE
-- event on Next ("Row 1, Notifiable Disease: This field is required").
--
-- 2026-09-22: pared down to what a national-level animal-disease-surveillance
-- record needs. Always shown, before any Event Type is picked: Ear Tag,
-- Species, Age, Event Type. Every other field is conditional on Event Type
-- ("show": event_type notEmpty/equals/notEquals) so a blank Add dialog is just
-- those four -- nothing renders until Event Type is chosen. Disease and
-- Notifiable Disease (DISEASE only) are the diagnostic content of a DISEASE
-- event and Ethiopia's OIE notifiable-disease reporting duty depends on that
-- flag being captured. Date of Onset / Date of Resolution are required
-- whenever shown (hidden only for RECOVERY / TREATMENT respectively), giving:
--   DISEASE    onset + resolution required
--   INJURY     onset + resolution required
--   TREATMENT  onset required (no resolution field)
--   RECOVERY   resolution required (no onset field)
-- Treatment Administered, Veterinarian / Officer, Location, Location Details
-- and Notes (2026-09-22 follow-up) are back too, all five gated on the same
-- single condition -- event_type notEmpty -- so nothing beyond Ear Tag /
-- Species / Age / Event Type renders until an Event Type is picked; optional
-- in every case, not required. Treatment Administered no longer has its own
-- RECOVERY exclusion: the dialog-table condition engine (compiled staff-ui,
-- see bt()/br() in the bundle) evaluates a field's "show"/"hide" actions in
-- array order and lets the LAST one win outright -- it does not AND multiple
-- conditions -- so a second action meant to narrow "shown" to "shown and not
-- RECOVERY" instead replaced it, and with event_type still blank
-- ("" !== "RECOVERY") the field showed before any Event Type was chosen.
-- One condition per field only, from here on.
-- Generated from the seed line; keep the two in sync.
UPDATE "public"."g2p_register_sections"
SET section_ui_schema = '{"panels": [{"panels": [{"widgets": [{"widget": "dialog-table", "widget-id": "ls_health_event_details_table", "widget-type": "dialog-table", "widget-label": "Health Event Details", "widget-readonly": false, "widget-data-path": "a40e4a02-1b82-5b31-89df-71624bd96545.records", "widget-data-columns": [{"widget": "text", "column-key": "ear_tag_id", "widget-type": "input", "widget-label": "Ear Tag / Secondary Identifier", "widget-autofill": {"fields": {"age": "age", "species": "species"}, "matchField": "ear_tag_id", "sourceWidgetId": "ls_animal_details_table"}, "widget-readonly": false, "widget-required": false, "widget-data-path": "ear_tag_id", "widget-placeholder": "ET + 10 digits, e.g. ET0000000123", "widget-data-options": {"actions": [{"action": "require", "condition": {"field": "ear_tag_id", "operator": "empty"}}]}}, {"widget": "select", "column-key": "species", "widget-type": "input", "widget-label": "Species", "widget-readonly": true, "widget-data-path": "species", "widget-data-source": {"type": "api", "method": "POST", "params": {"page_size": 500, "attribute_id": "LIVESTOCK_SPECIES"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_id"}}, {"widget": "text", "column-key": "age", "widget-type": "input", "widget-label": "Age", "widget-readonly": true, "widget-data-path": "age"}, {"widget": "select", "column-key": "event_type", "widget-type": "input", "widget-label": "Event Type", "widget-readonly": false, "widget-required": false, "widget-data-path": "event_type", "widget-data-source": {"type": "static", "options": [{"label": "DISEASE", "value": "DISEASE"}, {"label": "INJURY", "value": "INJURY"}, {"label": "TREATMENT", "value": "TREATMENT"}, {"label": "RECOVERY", "value": "RECOVERY"}]}, "widget-data-options": {"actions": [{"action": "require", "condition": {"field": "event_type", "operator": "empty"}}]}}, {"widget": "select", "column-key": "disease_type", "widget-type": "input", "widget-label": "Disease", "widget-readonly": false, "widget-data-path": "disease_type", "widget-data-source": {"type": "api", "method": "POST", "params": {"page_size": 500, "attribute_id": "LIVESTOCK_DISEASE"}, "service": "attributes", "endpoint": "values", "labelKey": "value_display", "valueKey": "value_id"}, "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "event_type", "value": "DISEASE", "operator": "equals"}}, {"action": "require", "condition": {"field": "event_type", "value": "DISEASE", "operator": "equals"}}]}}, {"widget": "date", "column-key": "date_onset", "widget-type": "input", "widget-label": "Date of Onset", "widget-readonly": false, "widget-data-path": "date_onset", "widget-data-format": {"dateFormat": "DD/MM/YYYY", "inputMethod": "picker", "dateConstraint": "past-only"}, "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "event_type", "value": "RECOVERY", "operator": "notEquals"}}, {"action": "require", "condition": {"field": "event_type", "value": "RECOVERY", "operator": "notEquals"}}]}, "widget-data-placeholder": "dd_mm_yyyy"}, {"widget": "date", "column-key": "date_resolution", "widget-type": "input", "widget-label": "Date of Resolution", "widget-readonly": false, "widget-data-path": "date_resolution", "widget-data-format": {"dateFormat": "DD/MM/YYYY", "inputMethod": "picker"}, "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "event_type", "value": "TREATMENT", "operator": "notEquals"}}, {"action": "require", "condition": {"field": "event_type", "value": "TREATMENT", "operator": "notEquals"}}]}, "widget-data-validation": {"notBeforeField": "date_onset", "notBeforeFieldMessage": "Date of Resolution cannot be before Date of Onset"}, "widget-data-placeholder": "dd_mm_yyyy"}, {"widget": "radio", "column-key": "is_notifiable", "widget-type": "input", "widget-label": "Notifiable Disease", "widget-readonly": false, "widget-data-path": "is_notifiable", "widget-data-source": {"type": "static", "options": [{"label": "YES", "value": true}, {"label": "NO", "value": false}]}, "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "event_type", "value": "DISEASE", "operator": "equals"}}, {"action": "require", "condition": {"field": "event_type", "value": "DISEASE", "operator": "equals"}}]}}, {"widget": "text", "column-key": "treatment", "widget-type": "input", "widget-label": "Treatment Administered", "widget-readonly": false, "widget-data-path": "treatment", "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "event_type", "operator": "notEmpty"}}]}}, {"widget": "text", "column-key": "veterinarian_name", "widget-type": "input", "widget-label": "Veterinarian / Officer", "widget-readonly": false, "widget-data-path": "veterinarian_name", "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "event_type", "operator": "notEmpty"}}]}}, {"widget": "select", "column-key": "location", "widget-type": "input", "widget-label": "Location", "widget-readonly": false, "widget-data-path": "location", "widget-data-source": {"type": "static", "options": [{"label": "HOME", "value": "HOME"}, {"label": "VETERINARY", "value": "VETERINARY"}, {"label": "MARKET", "value": "MARKET"}, {"label": "FIELD", "value": "FIELD"}, {"label": "QUARANTINE_CENTER", "value": "QUARANTINE_CENTER"}, {"label": "OTHER", "value": "OTHER"}]}, "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "event_type", "operator": "notEmpty"}}]}}, {"widget": "text", "column-key": "location_details", "widget-type": "input", "widget-label": "Location Details", "widget-readonly": false, "widget-data-path": "location_details", "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "event_type", "operator": "notEmpty"}}]}}, {"widget": "text", "column-key": "notes", "widget-type": "input", "widget-label": "Notes", "widget-readonly": false, "widget-data-path": "notes", "widget-data-options": {"actions": [{"action": "show", "condition": {"field": "event_type", "operator": "notEmpty"}}]}}], "widget-data-operations": {"add": true, "edit": true, "remove": true}, "widget-data-dialog-title-add": "Add Health Event Details", "widget-data-dialog-title-edit": "Edit Health Event Details"}], "panel-id": "vertical_panel_ls_health_event_details_1", "panel-orientation": "vertical"}], "panel-id": "horizontal_panel_ls_health_event_details", "panel-orientation": "horizontal"}], "section-id": "livestock_health_event_details_section_01", "section-title": "Health Event Details", "section-editable": true, "section-required-for-submit": false}'::jsonb
WHERE section_id = 'livestock_health_event_details_section_01';
